MODEL:
  TYPE: MOAT
  NAME: moat_3_224
  DROP_PATH_RATE: 0.7
  NUM_CLASSES: 45
  MOAT:
    EMBED_DIM: 160
    DEPTHS: (2, 12, 28, 2)
    DIM_HEAD: 32
    WINDOW_SIZE: (7, 7)
    USE_WINDOW: False
    POOL: "avg"
    CHANNELS: (160, 320, 640, 1280)