MODEL:
  TYPE: MOAT
  NAME: moat_2_224
  DROP_PATH_RATE: 0.5
  NUM_CLASSES: 45
  MOAT:
    EMBED_DIM: 128
    DEPTHS: (2, 6, 14, 2)
    DIM_HEAD: 32
    WINDOW_SIZE: (7, 7)
    USE_WINDOW: False
    POOL: "avg"
    CHANNELS: (128, 256, 512, 1024)