MODEL:
  TYPE: MOAT
  NAME: moat_1_224
  DROP_PATH_RATE: 0.3
  NUM_CLASSES: 45
  MOAT:
    EMBED_DIM: 64
    DEPTHS: (2, 6, 14, 2)
    DIM_HEAD: 32
    WINDOW_SIZE: (7, 7)
    USE_WINDOW: False
    POOL: "avg"
    CHANNELS: (96, 192, 384, 768)