MODEL:
  TYPE: MOAT
  NAME: tiny_moat_2_224
  DROP_PATH_RATE: 0.0
  NUM_CLASSES: 45
  MOAT:
    EMBED_DIM: 56
    DEPTHS: (2, 3, 7, 2)
    DIM_HEAD: 32
    WINDOW_SIZE: (7, 7)
    USE_WINDOW: False
    POOL: "avg"
    CHANNELS: (56, 112, 224, 448)